// AUTH
export const AUTHENTICATE = 'AUTHENTICATE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_CONFIRM = 'AUTH_CONFIRM';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Profile
export const SET_PROFILE = 'SET_PROFILE';
export const SELECT_PROFILE_MODAL = 'SELECT_PRODUCT_MODAL';

// Organizations
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';

// Organization Groups
export const SET_GROUPS = 'SET_GROUPS';

// Measurement System
export const SET_MEASUREMENT = 'SET_MEASUREMENT';

// Products
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ON_SELECT_PRODUCTS = 'ON_SELECT_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const COPY_PRODUCT = 'COPY_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CLEAR_PRODUCT_FORM = 'CLEAR_PRODUCT_FORM';
export const SET_PRODUCT_FORM = 'SET_PRODUCT_FORM';
export const FILL_PRODUCT_FORM = 'FILL_PRODUCT_FORM';
export const SET_PRODUCT_SELECT_FORM = 'SET_PRODUCT_SELECT_FORM';

// PRODUCT CATEGORIES
export const SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES';

// Inquires
export const SET_INQUIRES = 'SET_INQUIRES';
export const ON_SELECT_INQUIRES = 'ON_SELECT_INQUIRES';
export const SELECT_INQUIRE_MODAL = 'SELECT_INQUIRE_MODAL';
export const SET_INQUIRE_FORM = 'SET_INQUIRE_FORM';
export const FILL_INQUIRE_FORM = 'FILL_INQUIRE_FORM';
export const CLEAR_INQUIRE_FORM = 'CLEAR_INQUIRE_FORM';
// export const SET_INQUIRE_PRODUCTS = 'SET_INQUIRE_PRODUCTS';

// Invoices
export const SET_INVOICES = 'SET_INVOICES';
export const ON_SELECT_INVOICES = 'ON_SELECT_INVOICES';
export const SELECT_INVOICE_MODAL = 'SELECT_INVOICE_MODAL';
export const SET_INVOICE_FORM = 'SET_INVOICE_FORM';
export const FILL_INVOICE_FORM = 'FILL_INVOICE_FORM';
export const CLEAR_INVOICE_FORM = 'CLEAR_INVOICE_FORM';

// Offers
export const SET_OFFERS = 'SET_OFFERS';
export const ON_SELECT_OFFERS = 'ON_SELECT_OFFERS';
export const SELECT_OFFER_MODAL = 'SELECT_OFFER_MODAL';

// Quotations
export const SET_QUOTATIONS = 'SET_QUOTATIONS';
export const ON_SELECT_QUOTATIONS = 'ON_SELECT_QUOTATIONS';
export const SELECT_QUOTATION_MODAL = 'SELECT_QUOTATION_MODAL';
export const SET_QUOTATION_FORM = 'SET_QUOTATION_FORM';
export const CLEAR_QUOTATION_FORM = 'CLEAR_QUOTATION_FORM';
export const FILL_QUOTATION_FORM = 'FILL_QUOTATION_FORM';

// MarketPlace
export const FOLLOW_COMPANY = 'FOLLOW_COMPANY';

// Modal
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const SELECT_MODAL = 'SELECT_MODAL';

// Drawer
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';

// Main data
export const ON_SELECT_CHANGE = 'ON_SELECT_CHANGE';

export const INITIAL_DATA = 'INITIAL_DATA';

// COUNTRIES
export const SET_COUNTRIES = 'SET_COUNTRIES';

// TARIFF NUMBERS
export const SET_TARICS = 'SET_TARICS';

// BARCODES
export const SET_BARCODES = 'SET_BARCODES';

// CURRENCIES
export const SET_CURRENCIES = 'SET_CURRENCIES';

// LANGUAGES
export const SET_LANGUAGES = 'SET_LANGUAGES';

// COMMON ACTIONS
export const INFO = 'INFO';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const DELETES = 'DELETES';
export const COPY = 'COPY';
